/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author David Sierra
 */
public class JFrameVendedor extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVendedor
     */
    public JFrameVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Vendedor = new javax.swing.JPanel();
        Vendedor = new javax.swing.JLabel();
        Id_Vendedor = new javax.swing.JLabel();
        Nombre_Vendedor = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Id_Vende = new javax.swing.JTextField();
        Nom_Vende = new javax.swing.JTextField();
        Ape_Vende = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        B_Mostrar = new javax.swing.JButton();
        B_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Vendedor.setBackground(new java.awt.Color(204, 255, 153));

        Vendedor.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Vendedor.setText("Vendedor");

        Id_Vendedor.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Id_Vendedor.setText("Identificacion");

        Nombre_Vendedor.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Nombre_Vendedor.setText("Nombres");

        Apellido.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Apellido.setText("Apellidos");

        Id_Vende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_VendeActionPerformed(evt);
            }
        });

        Nom_Vende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_VendeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Apellidos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        B_Mostrar.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        B_Mostrar.setText("Mostrar");
        B_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MostrarActionPerformed(evt);
            }
        });

        B_Buscar.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        B_Buscar.setText("Buscar");
        B_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_VendedorLayout = new javax.swing.GroupLayout(Panel_Vendedor);
        Panel_Vendedor.setLayout(Panel_VendedorLayout);
        Panel_VendedorLayout.setHorizontalGroup(
            Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VendedorLayout.createSequentialGroup()
                .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_VendedorLayout.createSequentialGroup()
                        .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_VendedorLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_VendedorLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre_Vendedor)
                                    .addComponent(Apellido)
                                    .addComponent(Id_Vendedor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Id_Vende)
                                    .addComponent(Nom_Vende, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(Ape_Vende))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_VendedorLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(B_Mostrar)
                        .addGap(65, 65, 65)
                        .addComponent(B_Buscar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        Panel_VendedorLayout.setVerticalGroup(
            Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_VendedorLayout.createSequentialGroup()
                        .addComponent(Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Id_Vende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre_Vendedor)
                            .addComponent(Nom_Vende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Apellido)
                            .addComponent(Ape_Vende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(Panel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Id_VendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_VendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_VendeActionPerformed

    private void Nom_VendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_VendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_VendeActionPerformed

    private void B_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_MostrarActionPerformed

    private void B_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Ape_Vende;
    public javax.swing.JLabel Apellido;
    public javax.swing.JButton B_Buscar;
    public javax.swing.JButton B_Mostrar;
    public javax.swing.JTextField Id_Vende;
    public javax.swing.JLabel Id_Vendedor;
    public javax.swing.JTextField Nom_Vende;
    public javax.swing.JLabel Nombre_Vendedor;
    public javax.swing.JPanel Panel_Vendedor;
    public javax.swing.JLabel Vendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
