/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author SENA
 */
public class Vendedor1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendedor1
     */
    public Vendedor1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Info = new javax.swing.JTable();
        B_Mostrar = new javax.swing.JButton();
        B_Buscar = new javax.swing.JButton();
        Vendedor = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Id_Vendedor = new javax.swing.JLabel();
        Nombre_Vendedor = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Id_Vende = new javax.swing.JTextField();
        Nom_Vende = new javax.swing.JTextField();
        Ape_Vende = new javax.swing.JTextField();

        setClosable(true);

        Tabla_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Apellidos"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Info);

        B_Mostrar.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        B_Mostrar.setText("Mostrar");
        B_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MostrarActionPerformed(evt);
            }
        });

        B_Buscar.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        B_Buscar.setText("Buscar");
        B_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BuscarActionPerformed(evt);
            }
        });

        Vendedor.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Vendedor.setText("Vendedor");

        Guardar.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Id_Vendedor.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Id_Vendedor.setText("Identificacion");

        Nombre_Vendedor.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Nombre_Vendedor.setText("Nombres");

        Apellido.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        Apellido.setText("Apellidos");

        Id_Vende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_VendeActionPerformed(evt);
            }
        });

        Nom_Vende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_VendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Id_Vendedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Id_Vende))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Apellido)
                                            .addComponent(Nombre_Vendedor))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nom_Vende)
                                            .addComponent(Ape_Vende))))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(B_Mostrar)
                        .addGap(65, 65, 65)
                        .addComponent(B_Buscar)
                        .addGap(83, 83, 83)
                        .addComponent(Guardar)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Id_Vende, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre_Vendedor)
                            .addComponent(Nom_Vende, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ape_Vende, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_MostrarActionPerformed

    private void B_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_BuscarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void Id_VendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_VendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_VendeActionPerformed

    private void Nom_VendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_VendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_VendeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Ape_Vende;
    public javax.swing.JLabel Apellido;
    public javax.swing.JButton B_Buscar;
    public javax.swing.JButton B_Mostrar;
    public javax.swing.JButton Guardar;
    public javax.swing.JTextField Id_Vende;
    public javax.swing.JLabel Id_Vendedor;
    public javax.swing.JTextField Nom_Vende;
    public javax.swing.JLabel Nombre_Vendedor;
    public javax.swing.JTable Tabla_Info;
    public javax.swing.JLabel Vendedor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
